-- 초기 데이터 시드 파일 (상하차지/선사 코드)
-- 자동 생성됨

-- 기존 데이터 삭제
DELETE FROM location_codes;
DELETE FROM shipping_lines;
DELETE FROM dispatch_companies;

-- 협력업체 (배차업체) 삽입
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(유)오식도물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주) 제이디쉬핑라인', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)금길종합운수', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)다다물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)대경지엘에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)대명케이알', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)더블유비엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)도성물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)동방평택지사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)두레종합물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)디앤더블유로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)디에이엘로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)디케이물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)디티씨', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)라온티피엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)모아물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)백마종합물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)부강에너지', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)비앤피주성', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)비에스물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)비투라인', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)세광물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)세운물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)시우로지스틱', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)씨오엘티엔에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)아미인터내셔널', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)아이에스에이상운', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)아트윈로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)에스에이로지스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)에스와이물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)에이원로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)에이지엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)에이치에스해운', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)엘에스종합물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)원써클로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)유니글로벌로지스틱스코리아', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)유진로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)제이디아이글로벌', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)지엠엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)천경', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)카고맥스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)태웅로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)파크랜드', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)퍼시픽브리지', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)풍전비철', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('(주)한울로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('KCTC', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('경일글로벌로지스틱스주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('고성산업사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('그린오션로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('글로벌파트너로지스틱스 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('나래물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('대야글로벌', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('더로지스 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('더로케트', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('동방 익스프레스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('동원로엑스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('동진선박(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('동화로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('디앤케이물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('디에이치글로벌로지스틱스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('람세스물류(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('로지스팟 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('로지아이솔루션', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('롯데글로벌로지스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('루크인터내셔널코리아 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('미르시스템(대우로지스틱스)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('백승운수', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('범진물류(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('벨라이트', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('보림필터산업', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('본덱스글로벌코리아 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('부산캐리어', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('부산항터미널 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('삼인 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('삼인로지텍', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('세방육운', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('세원로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('송도물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('스타콩코드코리아 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('시노트란스코리아쉬핑(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('신아해운(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('씨아이지컨테이너라인즈 주식회사(CIG Container Line', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('씨에스글로벌로지스틱스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('씨에이치로빈슨코리아(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('씨제이대한통운(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('알지글로벌 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('앤씨티국제운송(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('양양운수(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에스더블유로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에스엠에이치', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에스지로지스틱', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에스지종합물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에이왓글로벌로지스틱스코리아(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('에이치엔엘트랜스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('영도머티리얼즈(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('온누리로지스틱스 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('와이에스엘로지텍 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('와이엠익스프레스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('우원해운항공(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('우진글로벌로지스틱스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('원올테크플러스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('유가로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('유진로지스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('율세', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('이레물류(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('이코노해운(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('이콜트에스앤티㈜', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('인터지스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('제이더블유제이로지스틱스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('제이맥스해운 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('제이앤지엘에스 주시회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('제이원로지스틱스 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('제주오케이물류 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주성씨앤에어주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 고성산업', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 다원로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 도성물류(김해지점)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 동주글로벌로지스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 디더블유엘글로벌', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 로지피아', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 부원글로벌', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 산내원', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 씨에이치앨', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 씨엘케이인터내셔널', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 씨케이팬아시아씨에프씨', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 아그리씨엔에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 아이멕스인터내셔널', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 아이바닥', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 알티에스지엘에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 양명로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 에버플로우로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 에스티로지텍', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 에이에이엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 오티에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 웅진북센', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 제닉스해운항공', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 제이앤케이로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 제이투씨앤에어', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 조이웍스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 지엔글로벌로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 케이트란스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 팰콘프레이트 (FALCON FREIGHT CO.,LTD)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사 현대정밀', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사엘엑스판토스부산신항물류센터', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('주식회사클라우드지엘에스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('중앙국제운송(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('중앙로지스틱스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('지더블유코퍼레이션㈜', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('지엠엘', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('창신로지스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('천일정기화물', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('칼트로지스부산 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('케이투로직스(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('코스타해운항공(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('태성종합물류', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('토탈로직스', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('투엠글로벌 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('한국일본통운(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('한타특수운송', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('항만물류주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('해광로지스틱(주)', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('현대정밀화학 주식회사', '일반', '');
INSERT OR IGNORE INTO dispatch_companies (name, payment_level, notes) VALUES ('혜원글로벌 주식회사', '일반', '');

-- 상하차지 코드 삽입
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('허치슨감만', 'Z9', '백승운수');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('BCT', 'BC', '(유)오식도물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('BIDC', 'BF', '(주) 제이디쉬핑라인');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('BIT', 'BT', '(주)금길종합운수');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('BNCT', 'BB', '(주)다다물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('DGT', 'TG', '(주)대경지엘에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('DPCT', 'DB', '(주)대명케이알');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('E1', 'E1', '(주)더블유비엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('GW', 'W9', '(주)도성물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('ICT', 'Y25', '(주)동방평택지사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('KBCT', 'P', '(주)두레종합물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('KCTC부곡', 'B13', '(주)디앤더블유로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('KCTC우암', 'B4', '(주)디에이엘로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('KIT', '25', '(주)디케이물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('KWCT', '25', '(주)디티씨');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('MS디스트리파크', 'MS', '(주)라온티피엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('PCTC', 'PC', '(주)모아물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('PNC', 'PN', '(주)백마종합물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('PNIT', 'KP', '(주)부강에너지');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('SNCT', 'NN', '(주)비앤피주성');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('YSL부곡', 'YL', '(주)비에스물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('강서미음', 'ME', '(주)비투라인');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('강서화전', 'ME', '(주)세광물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경기광주', 'MF', '(주)세운물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경기오산', '1I', '(주)시우로지스틱');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경남창녕', 'C0', '(주)씨오엘티엔에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경북구미', '1A', '(주)아미인터내셔널');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경북영주', 'J2', '(주)아이에스에이상운');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경산남천면', 'SA', '(주)아트윈로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경주', 'KU', '(주)에스에이로지스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경주외동읍', 'KU', '(주)에스와이물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경주천북', 'KU', '(주)에이원로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('고양', 'K#', '(주)에이지엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('공주', 'ZB', '(주)에이치에스해운');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('광명', 'Q0', '(주)엘에스종합물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('광양', 'KW', '(주)원써클로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('광주', 'QP', '(주)유니글로벌로지스틱스코리아');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('구미', '1A', '(주)유진로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('군산', 'QX', '(주)제이디아이글로벌');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('군포', '1C', '(주)지엠엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('극동 CY', 'K2', '(주)천경');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('기장', 'QQ', '(주)카고맥스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김천', 'BZ', '(주)태웅로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김포', 'P3', '(주)파크랜드');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김포대곶', 'P3', '(주)퍼시픽브리지');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김포월곶', 'P3', '(주)풍전비철');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김해', 'KQ', '(주)한울로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김해상동', 'JZ', 'KCTC');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김해안동', 'JZ', '경일글로벌로지스틱스주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('김해진영', 'J0', '고성산업사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('남양주', 'JX', '그린오션로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('뉴대원CY', 'N1', '글로벌파트너로지스틱스 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('당진', 'DJ', '나래물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대구', 'DG', '대야글로벌');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대구달성군', 'DG', '더로지스 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대전', 'DN', '더로케트');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대전대덕', 'DZ', '동원로엑스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대전대덕구', 'DN', '동진선박(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('대통부곡', 'B5', '동화로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('동부 PECT CY', 'D9', '디에이치글로벌로지스틱스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('동부부곡', 'B0', '람세스물류(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('마산항5부두', 'MQ', '로지스팟 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('무안', 'MA', '로지아이솔루션');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('밀양', 'MY', '롯데글로벌로지스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('봉화', '2R', '루크인터내셔널코리아 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부곡', 'BE', '미르시스템(대우로지스틱스)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부곡국보', 'B12', '범진물류(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부곡양양', 'B8', '벨라이트');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부산강서', 'PP', '보림필터산업');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부산강서구', 'PP', '본덱스글로벌코리아 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부산사상구', 'PP', '부산캐리어');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부산진역', 'W', '부산항터미널 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부원글로벌', 'BX', '삼인 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('부천', 'BUC', '삼인로지텍');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('북항쿨스타쵸', 'F2', '세방육운');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('서울', 'SU', '세원로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('서울성동구', '3K', '송도물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('서울역삼동', '5K', '스타콩코드코리아 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('세방부곡', 'B11', '시노트란스코리아쉬핑(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('세방신항', 'S2', '신아해운(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('세양석대', 'F2', '씨아이지컨테이너라인즈 주식회사(CIG Container Line');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('세종시', 'SG', '씨에스글로벌로지스틱스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('수원', 'SX', '씨에이치로빈슨코리아(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('수원권선구', 'SX', '씨제이대한통운(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('시흥', 'SH', '알지글로벌 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('씨엠케이로지스틱스', 'CM', '앤씨티국제운송(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('아산', 'AS', '양양운수(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('안산', 'AS1', '에스더블유로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('안산단원구', 'AS1', '에스엠에이치');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('안성', 'AN', '에스지로지스틱');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('안성원곡면', 'AN', '에스지종합물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('안성죽산면', 'AN', '에이왓글로벌로지스틱스코리아(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양산', 'C3', '에이치엔엘트랜스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양산물금', 'C3', '영도머티리얼즈(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양산유산', 'C3', '온누리로지스틱스 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양양부곡', 'B8', '와이에스엘로지텍 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양주', 'Y5', '와이엠익스프레스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('양주광적면', 'Y5', '우원해운항공(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('에스엘피지엘씨', 'SR', '우진글로벌로지스틱스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('여주', 'UZ', '원올테크플러스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('영진 CY', 'YC', '유가로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('영천', 'Q7', '유진로지스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('오산', '1I', '율세');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('옥천', 'OC', '이레물류(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('완주', '1G', '이코노해운(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('용인', 'YN', '이콜트에스앤티㈜');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('울산', 'WS', '인터지스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('원주', 'W1', '제이더블유제이로지스틱스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('음성', 'OS', '제이맥스해운 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('음성/음성', 'OS', '제이앤지엘에스 주시회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('의왕', '1B', '제이원로지스틱스 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('이천', 'IV', '제주오케이물류 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('익산', 'IZ', '주성씨앤에어주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천', 'IX', '주식회사 고성산업');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천 부평', '72', '천일정기화물');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천공항', 'AI', '주식회사 도성물류(김해지점)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천남동', '14', '주식회사 동주글로벌로지스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천더로지스', 'T2', '주식회사 디더블유엘글로벌');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천서구', 'IK', '주식회사 로지피아');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천승진CY', 'IS', '주식회사 부원글로벌');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천컨테이너터미널', 'Y25', '주식회사 산내원');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인천한진', 'NJ', '주식회사 씨에이치앨');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인터7부두', 'IN', '주식회사 씨엘케이인터내셔널');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('인터부곡', 'B6', '주식회사 씨케이팬아시아씨에프씨');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('전북군산', 'QX', '주식회사 아그리씨엔에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('전북임실', 'ZS', '주식회사 아이멕스인터내셔널');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('정선', 'J4', '주식회사 아이바닥');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('정읍', 'EP', '주식회사 알티에스지엘에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('제주구좌읍', 'JJ', '주식회사 양명로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('지더블유코퍼레이션', 'W9', '주식회사 에버플로우로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('진례', 'KQ', '주식회사 에스티로지텍');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('창원', 'Y1', '주식회사 에이에이엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('천경부곡', 'C1', '주식회사 오티에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('천안', 'NO', '주식회사 웅진북센');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('천안동남구', 'NO', '주식회사 제닉스해운항공');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('천일부곡', 'B2', '주식회사 제이앤케이로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('청도', 'CD', '주식회사 제이투씨앤에어');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('청주', 'CJ', '주식회사 조이웍스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충남서산', 'SV', '주식회사 지엔글로벌로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충남홍성', 'ZH', '주식회사 케이트란스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충북음성', 'OS', '주식회사 팰콘프레이트 (FALCON FREIGHT CO.,LTD)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충북진천', 'JC', '주식회사 현대정밀');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충북청주흥덕구', 'CJ', '주식회사엘엑스판토스부산신항물류센터');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('충주', 'ZQ', '주식회사클라우드지엘에스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('칠곡', 'Q3', '중앙국제운송(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('투엠글로벌', 'TM', '중앙로지스틱스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('파주', 'PJ', '지더블유코퍼레이션㈜');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('페어허브CFS', 'PZ', '지엠엘');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('평택', 'PT', '창신로지스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('평택포승읍', 'PT', '창신로지스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('포천', 'OQ', '칼트로지스부산 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('포항남구', 'PH', '케이투로직스(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('하남', 'AA', '코스타해운항공(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('한진부곡', 'B7', '태성종합물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('한진신항', 'HN', '토탈로직스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('한타부곡', 'B6', '투엠글로벌 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('한타신항', 'VZ', '한국일본통운(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('한타중부', 'HC', '한타특수운송');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('함안', 'HA', '항만물류주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('현대부곡', 'GH', '해광로지스틱(주)');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('현대신항', 'HP', '현대정밀화학 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('화성', 'HWA', '혜원글로벌 주식회사');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('화성동탄면', 'HWA', '동방 익스프레스');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('신국제여객', '81', '디앤케이물류');
INSERT OR IGNORE INTO location_codes (name, code, dispatch_company) VALUES ('경산', 'QK', '주식회사 다원로직스');

-- 선사 코드 삽입
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ANL', 'ANLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('APL', 'APLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('APS', 'APS');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CKL', 'CKCO');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CMA', 'CMAL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CMA', 'CMA');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CNC', 'CNCL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('COH', 'COHE');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('COS', 'COSU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CSX', 'CSX');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('CUL', 'CUL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('DJS', 'DJSC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('DWS', 'DOOW');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('DYS', 'PCSL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('EAS', 'EASL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('EMC', 'EVER');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ESL', 'ESLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ETC', 'ETC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('FEO', 'FESU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('GFS', 'GFS');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HAD', 'HDS');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HAPAG', 'HLCU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HAS', 'HASL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HEUNG-A', 'HASL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HLC', 'HLCU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HMM', 'HDMU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HSD', 'HSD');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('HSL', 'HSLI');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('IAL', 'IALU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('JCS', 'JCSC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('KFC', 'CM1');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('KMD', 'KMTC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('MAE', 'MAEU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('MSC', 'MSCU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('NSL', 'NSSL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ONE', 'ONE');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ONE-LINE', 'ONE');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('OOCL', 'OOLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('OOL', 'OOLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('PAN', 'PSLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('PCL', 'PCLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('PEL', 'PEL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('PIL', 'PILK');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('POL', 'PANO');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('RCL', 'RCLK');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SFK', 'SOFA');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SIT', 'SITC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SITC', 'SITC');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SKR', 'SNKO');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SML', 'SM');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SNL', 'SNLS');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SSN', 'SSNT');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('TSL', 'TSL');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('TYS', 'TYSP');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('VSS', 'VSS');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('WHL', 'WHLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('WSL', 'WEST');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('XXXX', 'XXXX');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('YML', 'YMLU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('ZIM', 'ZIMU');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('SIF', 'SIF');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('RSSA', 'RSA');
INSERT OR IGNORE INTO shipping_lines (name, code) VALUES ('BEN', 'BEN');